services:
  - type: web
    name: petsister-backend
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_KEY
        value: base64:fDhKaLEdxIPDIB9hZq0DGudmrD/vdO7lp2cA5UAsH3U=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sql12786247
      - key: DB_USERNAME
        value: sql12786247
      - key: DB_PASSWORD
        value: 6LwqPwP1m4
